--A101   24   ¥Î«—«◊∞¯(KE)
SELECT * FROM AIRPLANE;

SELECT * FROM COURSE;

--2022091900001   C999   P2022001   A1   ±Ë±Ë±Ë   123   123   N
SELECT * 
FROM RESERVATION;

CREATE OR REPLACE VIEW VW_GETREMAIN
AS
SELECT Q.*, NVL(Q.SEAT_TOTAL - T.CNT,Q.SEAT_TOTAL) SEAT_REMAIN
FROM
(
    --P2022001   ICN   2022/09/14   14:00   PEK   16:15   A101   350000   914KM   21
    SELECT A.COURSE_ID
         , COUNT(*) CNT
    FROM   RESERVATION A, COURSE B
    WHERE  A.COURSE_ID = B.COURSE_ID
    AND    A.CANCEL = 'N'
    GROUP BY A.COURSE_ID
) T,
(
    --P2022001   3
    SELECT C.COURSE_ID, C.DEP_LOCATION, C.DEP_DATE, C.DEP_TIME, C.AIRPORT_ID
         , C.ARR_TIME, C.AIRPLANE_ID, C.PRICE, C.DISTANCE, D.SEAT_TOTAL
    FROM   COURSE C, AIRPLANE D
    WHERE  C.AIRPLANE_ID = D.AIRPLANE_ID
) Q
WHERE Q.COURSE_ID = T.COURSE_ID(+);

SELECT * FROM VW_GETREMAIN;

--µ•¿Ã≈Õ∞° ≤ø¿Ã∏È WHERE¿ª ª©∞Ì Ω««‡
UPDATE COURSE A
SET    A.SEAT_REMAIN = (
            SELECT B.SEAT_REMAIN FROM VW_GETREMAIN B
            WHERE  B.COURSE_ID = A.COURSE_ID
        )
WHERE  A.COURSE_ID = 'P2022001';